/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.c5.juustofraktaalit.kali;

import fi.c5.juustofraktaalit.fraktaalit.FraktaaliTyyppi;
import fi.c5.juustofraktaalit.hajauttaja.Hajauttaja;
import fi.c5.juustofraktaalit.hajauttaja.Kuvapinta;
import fi.c5.juustofraktaalit.hajauttaja.Suorittaja;
import fi.c5.juustofraktaalit.hajauttaja.TyoMaarays;
import fi.c5.juustofraktaalit.hajauttaja.TyoVaihe;

/**
 *
 * @author Teemu Heikkilä
 */
public class Fraktaaliselain extends javax.swing.JFrame {

    /**
     * Creates new form Fraktaaliselain
     */
    public Fraktaaliselain() {
        initComponents();
        this.tila = new Tilanne(this.tilaKentta);
        tila.asetaTila("Valmis!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asetusPaneeli = new javax.swing.JPanel();
        algoritmiOtsikko = new javax.swing.JLabel();
        algoritmiValinta = new javax.swing.JComboBox();
        hajautusOtsikko = new javax.swing.JLabel();
        renderoiNappi = new javax.swing.JButton();
        hajautusSlideri = new javax.swing.JSlider();
        tilaOtsikko = new javax.swing.JLabel();
        tilaKentta = new javax.swing.JTextField();
        liikuteltavaPaneeli = new javax.swing.JScrollPane();
        piirtaja = new fi.c5.juustofraktaalit.kali.Piirtaja();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juustofraktaalit");

        asetusPaneeli.setBorder(javax.swing.BorderFactory.createTitledBorder("Asetukset"));

        algoritmiOtsikko.setText("Algoritmi");

        algoritmiValinta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mandelbrot", "Julia" }));

        hajautusOtsikko.setText("Hajautus");

        renderoiNappi.setText("Renderöi");
        renderoiNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderoiNappiActionPerformed(evt);
            }
        });

        hajautusSlideri.setMaximum(16);
        hajautusSlideri.setMinimum(1);
        hajautusSlideri.setPaintLabels(true);
        hajautusSlideri.setPaintTicks(true);
        hajautusSlideri.setSnapToTicks(true);
        hajautusSlideri.setValue(1);
        hajautusSlideri.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                hajautusSlideriPropertyChange(evt);
            }
        });

        tilaOtsikko.setText("Tila");

        tilaKentta.setEditable(false);
        tilaKentta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilaKenttaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout asetusPaneeliLayout = new javax.swing.GroupLayout(asetusPaneeli);
        asetusPaneeli.setLayout(asetusPaneeliLayout);
        asetusPaneeliLayout.setHorizontalGroup(
            asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asetusPaneeliLayout.createSequentialGroup()
                .addComponent(algoritmiOtsikko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algoritmiValinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(renderoiNappi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(asetusPaneeliLayout.createSequentialGroup()
                .addGroup(asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hajautusOtsikko)
                    .addComponent(tilaOtsikko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hajautusSlideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tilaKentta, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        asetusPaneeliLayout.setVerticalGroup(
            asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asetusPaneeliLayout.createSequentialGroup()
                .addGroup(asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(asetusPaneeliLayout.createSequentialGroup()
                        .addGroup(asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(algoritmiOtsikko)
                            .addComponent(algoritmiValinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hajautusOtsikko)
                            .addComponent(hajautusSlideri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(asetusPaneeliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(renderoiNappi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(asetusPaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tilaOtsikko)
                    .addComponent(tilaKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout piirtajaLayout = new javax.swing.GroupLayout(piirtaja);
        piirtaja.setLayout(piirtajaLayout);
        piirtajaLayout.setHorizontalGroup(
            piirtajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        piirtajaLayout.setVerticalGroup(
            piirtajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        liikuteltavaPaneeli.setViewportView(piirtaja);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asetusPaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(liikuteltavaPaneeli)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(liikuteltavaPaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asetusPaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renderoiNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderoiNappiActionPerformed
        tila.asetaTila("Renderöinti aloitettu!");
        TyoMaarays t = new TyoMaarays(FraktaaliTyyppi.MANDELBROT, null, new Kuvapinta(this.piirtaja.getWidth(), this.piirtaja.getHeight()), this.hajautusSlideri.getValue());
        t.asetaAlue(-1.0, 0.0, 1.5);
        Hajauttaja h = new Hajauttaja(t);
        Suorittaja v1 = new Suorittaja(h, this.tila, t, this.piirtaja);
        v1.execute();
        //
    }//GEN-LAST:event_renderoiNappiActionPerformed

    private void tilaKenttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilaKenttaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tilaKenttaActionPerformed

    private void hajautusSlideriPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_hajautusSlideriPropertyChange
        // TODO add your handling code here:
        System.out.println(evt.getPropertyName());
        if (evt.getPropertyName().equals("value")) {
            tila.asetaTila("Hajautus asetettu arvoon " + (Integer)evt.getNewValue()+" -> Renderöitäessä luodaan " + Math.pow((Integer)evt.getNewValue(), 2)+" säiettä.");            
        }
    }//GEN-LAST:event_hajautusSlideriPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algoritmiOtsikko;
    private javax.swing.JComboBox algoritmiValinta;
    private javax.swing.JPanel asetusPaneeli;
    private javax.swing.JLabel hajautusOtsikko;
    private javax.swing.JSlider hajautusSlideri;
    private javax.swing.JScrollPane liikuteltavaPaneeli;
    private fi.c5.juustofraktaalit.kali.Piirtaja piirtaja;
    private javax.swing.JButton renderoiNappi;
    private javax.swing.JTextField tilaKentta;
    private javax.swing.JLabel tilaOtsikko;
    // End of variables declaration//GEN-END:variables
    private Tilanne tila;
}
